spring:
  application:
    name: community
  datasource:
    url: jdbc:mysql://localhost:3306/community
    username: root
    password: wap-backend-deploy
  jpa:
    hibernate:
      ddl-auto: update
